import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import favicon from '@/public/assets/images/favicon.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  icons:[favicon.src],
  title: "Habit Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-gray-100'}>{children}</body>
    </html>
  );
}
